const fs = require('fs');
const path = require('path');

// List of English tech terms to flag (case insensitive)
const forbiddenTerms = [
  'endpoint',
  'vpn',
  'api',
  'database',
  'server',
  'client',
  'framework',
  'library',
  'algorithm',
  'variable',
  'function',
  'class',
  'object',
  'array',
  'string',
  'integer',
  'boolean',
  'null',
  'undefined',
  'error',
  'exception',
  'debug',
  'compile',
  'build',
  'deploy',
  'repository',
  'commit',
  'branch',
  'merge',
  'pull request',
  'issue',
  'bug',
  'feature',
  'version',
  'release',
  'update',
  'install',
  'package',
  'module',
  'dependency',
  'script',
  'command',
  'terminal',
  'console',
  'log',
  'print',
  'input',
  'output',
  'file',
  'folder',
  'directory',
  'path',
  'url',
  'link',
  'website',
  'browser',
  'cache',
  'cookie',
  'session',
  'authentication',
  'authorization',
  'login',
  'logout',
  'user',
  'admin',
  'password',
  'email',
  'notification',
  'message',
  'chat',
  'forum',
  'post',
  'comment',
  'like',
  'share',
  'follow',
  'profile',
  'account',
  'settings',
  'configuration',
  'option',
  'default',
  'custom',
  'template',
  'theme',
  'plugin',
  'extension',
  'widget',
  'component',
  'element',
  'tag',
  'attribute',
  'property',
  'method',
  'event',
  'handler',
  'callback',
  'promise',
  'async',
  'await',
  'loop',
  'condition',
  'statement',
  'expression',
  'operator',
  'syntax',
  'keyword',
  'comment',
  'documentation',
  'readme',
  'license',
  'changelog',
  'todo',
  'fix',
  'refactor',
  'test',
  'unit test',
  'integration test',
  'e2e test',
  'ci',
  'cd',
  'pipeline',
  'workflow',
  'action',
  'job',
  'step',
  'artifact',
  'environment',
  'secret',
  'token',
  'key',
  'certificate',
  'ssl',
  'http',
  'https',
  'ftp',
  'tcp',
  'udp',
  'ip',
  'dns',
  'domain',
  'host',
  'port',
  'socket',
  'connection',
  'request',
  'response',
  'header',
  'body',
  'json',
  'xml',
  'html',
  'css',
  'javascript',
  'typescript',
  'python',
  'java',
  'c++',
  'php',
  'ruby',
  'go',
  'rust',
  'kotlin',
  'swift',
  'dart',
  'flutter',
  'react',
  'vue',
  'angular',
  'node',
  'npm',
  'yarn',
  'webpack',
  'babel',
  'eslint',
  'prettier',
  'jest',
  'mocha',
  'cypress',
  'selenium',
  'docker',
  'kubernetes',
  'aws',
  'azure',
  'gcp',
  'firebase',
  'heroku',
  'vercel',
  'netlify',
  'github',
  'gitlab',
  'bitbucket',
  'slack',
  'discord',
  'zoom',
  'microsoft teams',
  'google meet',
  'skype',
  'whatsapp',
  'telegram',
  'twitter',
  'facebook',
  'instagram',
  'linkedin',
  'youtube',
  'tiktok',
  'reddit',
  'stackoverflow',
  'medium',
  'dev.to',
  'hackerrank',
  'leetcode',
  'codepen',
  'jsfiddle',
  'repl.it',
  'glitch',
  'codesandbox',
  'vscode',
  'sublime',
  'atom',
  'vim',
  'emacs',
  'intellij',
  'eclipse',
  'xcode',
  'android studio',
  'unity',
  'unreal',
  'blender',
  'photoshop',
  'illustrator',
  'figma',
  'sketch',
  'canva',
  'notion',
  'evernote',
  'trello',
  'jira',
  'asana',
  'monday',
  'clickup',
  'basecamp',
  'slack',
  'discord',
  'zoom',
  'microsoft teams',
  'google meet',
  'skype',
  'whatsapp',
  'telegram',
  'twitter',
  'facebook',
  'instagram',
  'linkedin',
  'youtube',
  'tiktok',
  'reddit',
  'stackoverflow',
  'medium',
  'dev.to',
  'hackerrank',
  'leetcode',
  'codepen',
  'jsfiddle',
  'repl.it',
  'glitch',
  'codesandbox',
  'vscode',
  'sublime',
  'atom',
  'vim',
  'emacs',
  'intellij',
  'eclipse',
  'xcode',
  'android studio',
  'unity',
  'unreal',
  'blender',
  'photoshop',
  'illustrator',
  'figma',
  'sketch',
  'canva',
  'notion',
  'evernote',
  'trello',
  'jira',
  'asana',
  'monday',
  'clickup',
  'basecamp'
];

// Function to get all .md files recursively
function getMdFiles(dirPath, arrayOfFiles = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach(file => {
    const fullPath = path.join(dirPath, file);
    if (fs.statSync(fullPath).isDirectory()) {
      arrayOfFiles = getMdFiles(fullPath, arrayOfFiles);
    } else if (file.endsWith('.md') || file.endsWith('.mdx')) {
      arrayOfFiles.push(fullPath);
    }
  });

  return arrayOfFiles;
}

// Check a file for forbidden terms
function checkFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const lowerContent = content.toLowerCase();
  const foundTerms = [];

  forbiddenTerms.forEach(term => {
    if (lowerContent.includes(term.toLowerCase())) {
      foundTerms.push(term);
    }
  });

  return foundTerms;
}

// Main function
function main() {
  const dirsToCheck = ['docs', 'blog'];
  let hasErrors = false;

  dirsToCheck.forEach(dir => {
    if (fs.existsSync(dir)) {
      const mdFiles = getMdFiles(dir);
      mdFiles.forEach(file => {
        const found = checkFile(file);
        if (found.length > 0) {
          console.error(`Found English terms in ${file}: ${found.join(', ')}`);
          hasErrors = true;
        }
      });
    }
  });

  if (hasErrors) {
    console.error('Content check failed: English tech terms found in .md files.');
    process.exit(1);
  } else {
    console.log('Content check passed: No English tech terms found.');
  }
}

main();